import express from "express";
import path from "path";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json({ limit: "25mb" }));

// Lazy Gemini client helper
let aiClient: GoogleGenAI | null = null;
function getGeminiClient(): GoogleGenAI {
  if (!aiClient) {
    aiClient = new GoogleGenAI({
      apiKey: process.env.GEMINI_API_KEY || "",
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });
  }
  return aiClient;
}

// Check health & model status
app.get("/api/health", (req, res) => {
  res.json({
    status: "ok",
    app: "Farhee Intelligent",
    creator: "PGV Creation (Batticaloa, Sri Lanka)",
    hasGeminiKey: Boolean(process.env.GEMINI_API_KEY),
    timestamp: new Date().toISOString(),
  });
});

// 1. AI Chat Endpoint
app.post("/api/chat", async (req, res) => {
  try {
    const { messages, systemPrompt } = req.body;
    if (!messages || !Array.isArray(messages)) {
      return res.status(400).json({ error: "Invalid messages format" });
    }

    const ai = getGeminiClient();
    const systemInstruction =
      systemPrompt ||
      `You are "Farhee Intelligent", a multi-functional modern AI assistant built with precision by PGV Creation (Batticaloa, Sri Lanka).
Your capabilities include coding, debugging, creative generation, audio & music concept generation, math, and intelligent conversation.
Formatting rules:
- Use clean Markdown with headers, bullet points, and code blocks with language identifiers.
- When explaining mathematical or scientific formulas, format them clearly.
- Maintain an encouraging, sophisticated, and insightful tone.
- Acknowledge your heritage as Farhee Intelligent engineered by PGV Creation when asked.`;

    const contents = messages.map((m: { role: string; content: string }) => ({
      role: m.role === "user" ? "user" : "model",
      parts: [{ text: m.content }],
    }));

    const response = await ai.models.generateContent({
      model: "gemini-3.7-flash",
      contents,
      config: {
        systemInstruction,
        temperature: 0.7,
        topP: 0.95,
      },
    });

    const reply = response.text || "I'm sorry, I couldn't process that response.";
    res.json({ reply });
  } catch (error: any) {
    console.error("Chat error:", error);
    res.status(500).json({
      error: error?.message || "Failed to generate chat response",
      fallbackReply:
        "Farhee Intelligent encountered a temporary network delay. Please verify your connection or try again in a moment.",
    });
  }
});

// 2. AI Code Generator Endpoint
app.post("/api/code/generate", async (req, res) => {
  try {
    const { prompt, language = "React", framework = "Tailwind CSS", includePreview = true } = req.body;
    if (!prompt) {
      return res.status(400).json({ error: "Prompt is required" });
    }

    const ai = getGeminiClient();
    const systemInstruction = `You are the specialized Code Generation Engine of Farhee Intelligent, crafted by PGV Creation.
Generate modern, production-grade, highly structured code based on the user's prompt.
Target language: ${language}.
Framework/Styling: ${framework}.

You MUST return a clean JSON object with this exact structure:
{
  "title": "Brief title of the code component/script",
  "language": "${language}",
  "code": "The primary clean, fully implemented code string without markdown backticks wrapping the whole JSON",
  "previewHtml": "If this is HTML/JS/CSS or React-renderable web code, provide a self-contained single-page HTML snippet with CDN styles/scripts (like Tailwind or React CDN) that can run directly inside an iframe sandbox preview. Otherwise empty string.",
  "explanation": "Markdown description of how this code works and architectural choices.",
  "features": ["Key feature 1", "Key feature 2", "Key feature 3"],
  "dependencies": ["package-a", "package-b"]
}
Ensure the JSON is valid, properly escaped, and strictly conformant.`;

    const response = await ai.models.generateContent({
      model: "gemini-3.7-flash",
      contents: `Generate code for: ${prompt}`,
      config: {
        systemInstruction,
        responseMimeType: "application/json",
        temperature: 0.2,
      },
    });

    let data;
    try {
      data = JSON.parse(response.text || "{}");
    } catch {
      data = {
        title: "Generated Code",
        language,
        code: response.text || "// Error parsing code structure",
        previewHtml: "",
        explanation: "Generated by Farhee Intelligent Code Generator.",
        features: ["Clean structure", "Optimized performance"],
        dependencies: [],
      };
    }

    res.json(data);
  } catch (error: any) {
    console.error("Code generation error:", error);
    res.status(500).json({
      error: error?.message || "Failed to generate code",
    });
  }
});

// 3. AI Bug Reporter & Fixer Endpoint
app.post("/api/code/fix-bug", async (req, res) => {
  try {
    const { code, errorMessage, language = "auto" } = req.body;
    if (!code && !errorMessage) {
      return res.status(400).json({ error: "Code or error message is required" });
    }

    const ai = getGeminiClient();
    const systemInstruction = `You are Farhee Intelligent's expert AI Bug Reporter & Code Fixer by PGV Creation.
Analyze the provided code and/or raw terminal error logs.
You MUST output a valid JSON with:
1) "cause": Clear, precise root-cause analysis explaining why the error occurred.
2) "correctedCode": The complete, corrected version of the code with clean formatting.
3) "explanation": Detailed line-by-line explanation of changes made.
4) "preventionTips": Array of 3-5 actionable bullet points on how to prevent this bug in the future (e.g. testing, typing, linting).
5) "severity": "High" | "Medium" | "Low"
6) "detectedLanguage": The detected programming language (e.g. "TypeScript", "Python", "React", "Rust").`;

    const userPrompt = `
BUG REPORT INPUT:
${code ? `=== BROKEN CODE ===\n${code}\n` : ""}
${errorMessage ? `=== ERROR / STACK TRACE ===\n${errorMessage}\n` : ""}
Detected/Target Language: ${language}
`;

    const response = await ai.models.generateContent({
      model: "gemini-3.7-flash",
      contents: userPrompt,
      config: {
        systemInstruction,
        responseMimeType: "application/json",
        temperature: 0.1,
      },
    });

    let result;
    try {
      result = JSON.parse(response.text || "{}");
    } catch {
      result = {
        cause: "Analysis parsing error",
        correctedCode: code || "",
        explanation: response.text || "Diagnostic output",
        preventionTips: ["Verify syntax", "Check type constraints", "Inspect dependencies"],
        severity: "Medium",
        detectedLanguage: language,
      };
    }

    res.json(result);
  } catch (error: any) {
    console.error("Bug Fixer error:", error);
    res.status(500).json({
      error: error?.message || "Failed to fix bug",
    });
  }
});

// 4. AI Image Generator & Enhancer Endpoint
app.post("/api/image/generate", async (req, res) => {
  try {
    const { prompt, style = "Cinematic", aspectRatio = "1:1", seed } = req.body;
    if (!prompt) {
      return res.status(400).json({ error: "Prompt is required" });
    }

    const ai = getGeminiClient();
    
    // Style presets configuration
    const styleKeywords: Record<string, string> = {
      Realistic: "photorealistic, hyper-detailed 8k photography, natural lighting, shot on 35mm lens, sharp focus, masterpiece",
      Anime: "modern anime aesthetic, vibrant studio ghibli and makoto shinkai style, cel shading, highly detailed line art",
      "3D Render": "octane render 3D, unreal engine 5, ray-traced lighting, volumetric shaders, ultra clean geometry, Pixar & Disney quality",
      Cyberpunk: "cyberpunk futuristic theme, neon lime and emerald liquid glow, obsidian dark atmosphere, holographic elements, detailed sci-fi cityscape",
      Cinematic: "dramatic cinematic movie still, anamorphic lens flare, rich depth of field, 8k resolution, IMAX color grading, atmospheric mood",
      DigitalArt: "digital concept art, intricate brushstrokes, atmospheric fantasy artstation trending",
    };

    const chosenStyle = styleKeywords[style] || styleKeywords.Cinematic;
    
    // Enhance prompt using Gemini
    let enhancedPrompt = prompt;
    try {
      const enhancementResponse = await ai.models.generateContent({
        model: "gemini-3.7-flash",
        contents: `Enhance this image prompt for a state-of-the-art text-to-image generator.
Original Prompt: "${prompt}"
Desired Style: "${style}" (${chosenStyle})
Return ONLY the final enhanced prompt in plain text without quotes or explanations.`,
      });
      enhancedPrompt = enhancementResponse.text?.trim() || prompt;
    } catch (e) {
      enhancedPrompt = `${prompt}, ${chosenStyle}`;
    }

    // Determine dimensions based on aspect ratio
    let width = 1024;
    let height = 1024;
    if (aspectRatio === "16:9") {
      width = 1280;
      height = 720;
    } else if (aspectRatio === "9:16") {
      width = 720;
      height = 1280;
    }

    const currentSeed = seed || Math.floor(Math.random() * 1000000);
    const encodedPrompt = encodeURIComponent(`${enhancedPrompt}, high quality, clean composition`);
    
    // Fast & free high-definition AI image provider via Pollinations.ai with model choice & seed
    const imageUrl = `https://image.pollinations.ai/prompt/${encodedPrompt}?width=${width}&height=${height}&seed=${currentSeed}&model=flux&nologo=true&enhance=false`;

    res.json({
      imageUrl,
      enhancedPrompt,
      originalPrompt: prompt,
      style,
      aspectRatio,
      width,
      height,
      seed: currentSeed,
    });
  } catch (error: any) {
    console.error("Image generation error:", error);
    res.status(500).json({
      error: error?.message || "Failed to generate image",
    });
  }
});

// 5. AI Music & Audio Generator Blueprint Endpoint
app.post("/api/music/generate", async (req, res) => {
  try {
    const { prompt, genre = "Cyberpunk Beats", duration = 30, tempo = 120 } = req.body;
    if (!prompt) {
      return res.status(400).json({ error: "Prompt is required" });
    }

    const ai = getGeminiClient();
    const systemInstruction = `You are Farhee Intelligent's Music & Audio Synthesizer AI created by PGV Creation (Batticaloa, Sri Lanka).
Generate a rich, structured composition blueprint for a musical piece based on the user's prompt.

You MUST return a JSON object with:
1) "title": A cool title for the track.
2) "genre": The musical genre.
3) "bpm": Recommended BPM tempo number (e.g. 80 - 150).
4) "key": Musical key (e.g., "C Minor", "F# Dorian", "A Minor").
5) "mood": Mood description.
6) "structure": Array of section names (e.g. ["Intro", "Verse / Synth Wave", "Chorus / Drop", "Outro"]).
7) "synthBlueprint": Object detailing synthesized sound design:
   - "bassType": "sub-saw" | "acid-square" | "warm-sine" | "fm-pluck"
   - "leadType": "neon-supersaw" | "ethereal-chime" | "lofi-triangle" | "pluck"
   - "drumPattern": "four-on-the-floor" | "breakbeat" | "half-time-lofi" | "cyber-electro"
   - "chordProgression": Array of chord names (e.g. ["Cm", "Ab", "Eb", "Bb"])
   - "melodyNotes": Array of MIDI/note names for melody sequences (e.g. ["C4", "Eb4", "G4", "Bb4", "C5", "G4", "Ab4", "F4"])
   - "bassNotes": Array of root notes (e.g. ["C2", "Ab1", "Eb2", "Bb1"])
8) "aiLyrics": Optional lyric verses or voiceover narration matching the mood (or empty if purely instrumental).
9) "audioCraftPrompt": Formatted prompt string for Suno/AudioCraft/MusicGen generators.`;

    const response = await ai.models.generateContent({
      model: "gemini-3.7-flash",
      contents: `Generate music blueprint for: "${prompt}". Preferred genre: ${genre}, duration target: ${duration}s, target BPM: ${tempo}`,
      config: {
        systemInstruction,
        responseMimeType: "application/json",
        temperature: 0.7,
      },
    });

    let musicData;
    try {
      musicData = JSON.parse(response.text || "{}");
    } catch {
      musicData = {
        title: "Farhee Cyber Symphony",
        genre,
        bpm: tempo || 124,
        key: "C Minor",
        mood: "Atmospheric & Futuristic",
        structure: ["Intro", "Pulse", "Synthesizer Lead", "Outro"],
        synthBlueprint: {
          bassType: "sub-saw",
          leadType: "neon-supersaw",
          drumPattern: "cyber-electro",
          chordProgression: ["Cm", "Ab", "Fm", "G7"],
          melodyNotes: ["C4", "D#4", "G4", "A#4", "C5", "G4", "F4", "D#4"],
          bassNotes: ["C2", "G#1", "F1", "G1"],
        },
        aiLyrics: "Through neon shadows of Batticaloa night,\nFarhee pulses in emerald light,\nSynthetic waves across the digital sea,\nCreation engineered for eternity.",
        audioCraftPrompt: `${genre}, ${prompt}, 120 bpm, electronic synthesizer, high production quality`,
      };
    }

    res.json(musicData);
  } catch (error: any) {
    console.error("Music generation error:", error);
    res.status(500).json({
      error: error?.message || "Failed to generate music blueprint",
    });
  }
});

// 6. AI Presentation Generator Endpoint
app.post("/api/presentation/generate", async (req, res) => {
  try {
    const { topic, slideCount = 6, theme = "emerald", audience = "General", tone = "Professional" } = req.body;
    if (!topic) {
      return res.status(400).json({ error: "Topic is required" });
    }

    const ai = getGeminiClient();
    const systemInstruction = `You are Farhee Intelligent's PowerPoint & Deck Presentation Architect by PGV Creation (Batticaloa, Sri Lanka).
Generate a comprehensive, high-impact slide deck outline based on the requested topic.

Return ONLY a valid JSON object with this exact structure:
{
  "title": "Compelling Presentation Title",
  "subtitle": "Informative Subtitle or Deck Pitch",
  "theme": "${theme}",
  "aspectRatio": "16:9",
  "author": "Farhee Intelligent (PGV Creation)",
  "slides": [
    {
      "slideNumber": 1,
      "layout": "title",
      "title": "Title of presentation",
      "subtitle": "Subtitle of the presentation",
      "bulletPoints": [],
      "tag": "Introduction",
      "notes": "Opening remarks for the speaker"
    },
    {
      "slideNumber": 2,
      "layout": "content",
      "title": "Clear Slide Heading",
      "subtitle": "Key takeaway context",
      "bulletPoints": [
        "First major point with rich detail",
        "Second major point with supporting statistics or rationale",
        "Third actionable takeaway"
      ],
      "metrics": [
        { "label": "Growth Index", "value": "+140%", "detail": "Year-over-Year" },
        { "label": "Efficiency", "value": "99.8%", "detail": "Operational uptime" }
      ],
      "tag": "Core Insight",
      "notes": "Detailed speaker notes for slide 2"
    }
  ]
}

Generate exactly ${slideCount} slides covering:
1. Title slide
2. Problem Statement / Market Opportunity
3. Solution Architecture / Key Value Pillars
4. Deep Dive / Execution Strategy
5. Results / Metrics / Timeline
6. Conclusion / Call to Action.

Ensure all bullet points are insightful, precise, and professional.`;

    const response = await ai.models.generateContent({
      model: "gemini-3.7-flash",
      contents: `Create presentation on: "${topic}". Audience: ${audience}, Tone: ${tone}, Slides: ${slideCount}`,
      config: {
        systemInstruction,
        responseMimeType: "application/json",
        temperature: 0.3,
      },
    });

    let presentationData;
    try {
      presentationData = JSON.parse(response.text || "{}");
    } catch {
      presentationData = {
        title: topic,
        subtitle: "Generated by Farhee Intelligent Presentation Engine",
        theme,
        aspectRatio: "16:9",
        author: "PGV Creation",
        slides: [
          {
            slideNumber: 1,
            layout: "title",
            title: topic,
            subtitle: "Strategic Overview & Roadmap",
            bulletPoints: [],
            notes: "Welcome everyone to today's briefing.",
          },
          {
            slideNumber: 2,
            layout: "content",
            title: "Executive Summary",
            subtitle: "Key objectives and priorities",
            bulletPoints: [
              "Harness modern AI to accelerate digital workflows and operational output.",
              "Ensure robust security, speed, and real-time accessibility across all devices.",
              "Deliver measurable ROI with intuitive user experience.",
            ],
            notes: "Emphasize our strategic focus areas.",
          },
        ],
      };
    }

    res.json(presentationData);
  } catch (error: any) {
    console.error("Presentation generation error:", error);
    res.status(500).json({
      error: error?.message || "Failed to generate presentation",
    });
  }
});

// 7. Audio Transcription (Voice to Text via Gemini)
app.post("/api/audio/transcribe", async (req, res) => {
  try {
    const { audioBase64, mimeType = "audio/webm", language = "auto" } = req.body;
    if (!audioBase64) {
      return res.status(400).json({ error: "audioBase64 data is required" });
    }

    const ai = getGeminiClient();
    const cleanBase64 = audioBase64.replace(/^data:audio\/[a-zA-Z0-9_-]+;base64,/, "");

    const response = await ai.models.generateContent({
      model: "gemini-3.5-transcribe",
      contents: [
        {
          inlineData: {
            mimeType,
            data: cleanBase64,
          },
        },
        {
          text: `Transcribe the spoken audio accurately into text. If the speaker speaks English, Tamil, Sinhala or any other language, transcribe in the spoken language accurately. Return ONLY the verbatim transcribed text without preamble or quotes.`,
        },
      ],
    });

    const transcript = response.text ? response.text.trim() : "";
    res.json({ transcript });
  } catch (error: any) {
    console.error("Audio transcription error:", error);
    res.status(500).json({
      error: error?.message || "Failed to transcribe audio",
    });
  }
});

// 8. Voice Conversation Mode Response Generator
app.post("/api/voice/chat", async (req, res) => {
  try {
    const { messages = [], personality = "natural", userSpeech = "" } = req.body;
    const ai = getGeminiClient();

    const systemInstruction = `You are Farhee Voice Agent, an ultra-responsive, intelligent, and natural conversational voice AI crafted by PGV Creation (Batticaloa, Sri Lanka).
Your replies will be SPOKEN ALOUD directly to the user in a live hands-free voice conversation.
Guidelines:
1. Keep replies concise, engaging, warm, and natural (1 to 3 spoken sentences per turn unless the user asks for a longer explanation).
2. Avoid using markdown formatting, bullet asterisks, code blocks, or URLs because this text is fed directly into a speech synthesis engine.
3. Be helpful, polite, and responsive with a friendly and knowledgeable personality.
4. If asked about your origin, proudly mention Farhee Intelligent by PGV Creation from Batticaloa, Sri Lanka.`;

    const contents = [
      ...messages.slice(-8).map((m: any) => ({
        role: m.role === "model" ? "model" : "user",
        parts: [{ text: m.content || "" }],
      })),
    ];

    if (userSpeech) {
      contents.push({
        role: "user",
        parts: [{ text: userSpeech }],
      });
    }

    const response = await ai.models.generateContent({
      model: "gemini-3.7-flash",
      contents,
      config: {
        systemInstruction,
        temperature: 0.7,
      },
    });

    const voiceReply = response.text ? response.text.trim() : "I am here with you. How can I help?";
    res.json({ reply: voiceReply });
  } catch (error: any) {
    console.error("Voice chat error:", error);
    res.status(500).json({
      error: error?.message || "Failed to generate voice response",
    });
  }
});

// Vite middleware / production static serving
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const { createServer: createViteServer } = await import("vite");
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Farhee Intelligent server running on http://localhost:${PORT}`);
  });
}

startServer();
