import React, { useState, useEffect, useRef } from 'react';
import ReactMarkdown from 'react-markdown';
import { 
  Code2, 
  Play, 
  Copy, 
  Check, 
  Download, 
  Sparkles, 
  Terminal, 
  Layers, 
  ExternalLink, 
  RefreshCw,
  Eye,
  FileCode,
  Zap,
  Maximize2
} from 'lucide-react';
import { GeneratedCodeResult } from '../types';
import { StorageService } from '../utils/storage';
import { safeApiPost, formatHttpStatus } from '../utils/api';
import { generateCodeWithGemini } from '../services/ai';

const LANGUAGES = [
  { id: 'React', label: 'React (TSX)', ext: 'tsx', template: 'Responsive animated analytics card' },
  { id: 'Python', label: 'Python', ext: 'py', template: 'FastAPI async authentication endpoint with JWT' },
  { id: 'HTML/CSS', label: 'HTML/CSS/JS', ext: 'html', template: 'Modern Neomorphic animated pricing table' },
  { id: 'Flutter', label: 'Flutter / Dart', ext: 'dart', template: 'Futuristic mobile crypto wallet card' },
  { id: 'C++', label: 'C++', ext: 'cpp', template: 'High-performance multithreaded queue processor' },
  { id: 'SQL', label: 'PostgreSQL / SQL', ext: 'sql', template: 'Optimized e-commerce inventory schema with triggers' },
  { id: 'TypeScript', label: 'TypeScript', ext: 'ts', template: 'Generic State Machine with typed transitions' },
  { id: 'Rust', label: 'Rust', ext: 'rs', template: 'Async Axum web server with graceful shutdown' },
];

export const CodeGenView: React.FC = () => {
  const [selectedLang, setSelectedLang] = useState('React');
  const [prompt, setPrompt] = useState('Create an interactive Glassmorphic Crypto Card with live price fluctuation, neon lime glowing accents, and copy address button.');
  const [framework, setFramework] = useState('Tailwind CSS');
  const [isLoading, setIsLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [activeTab, setActiveTab] = useState<'code' | 'preview' | 'explanation'>('code');
  const [generatedResult, setGeneratedResult] = useState<GeneratedCodeResult | null>(() => {
    const list = StorageService.getGeneratedCodes();
    return list[0] || null;
  });

  const previewIframeRef = useRef<HTMLIFrameElement>(null);

  const handleGenerate = async (customPrompt?: string) => {
    const p = customPrompt || prompt;
    if (!p.trim() || isLoading) return;

    setIsLoading(true);
    try {
      const data = await generateCodeWithGemini(p, selectedLang, framework);

      const codeItem: GeneratedCodeResult = {
        id: 'code-' + Date.now(),
        title: data.title || `${selectedLang} Component`,
        language: data.language || selectedLang,
        code: data.code || '// No code returned',
        previewHtml: data.previewHtml || (selectedLang === 'HTML/CSS' || selectedLang === 'React' ? data.code : ''),
        explanation: data.explanation || 'Generated by Farhee Intelligent',
        features: data.features || [],
        dependencies: data.dependencies || [],
        createdAt: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      };

      setGeneratedResult(codeItem);
      StorageService.saveGeneratedCode(codeItem);
      if (codeItem.previewHtml) {
        setActiveTab('preview');
      } else {
        setActiveTab('code');
      }
    } catch (err: any) {
      console.error('[Farhee CodeGen Error]:', err);
    } finally {
      setIsLoading(false);
    }
  };

  const handleCopyCode = () => {
    if (!generatedResult) return;
    navigator.clipboard.writeText(generatedResult.code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadFile = () => {
    if (!generatedResult) return;
    const langObj = LANGUAGES.find(l => l.id === generatedResult.language) || { ext: 'txt' };
    const blob = new Blob([generatedResult.code], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${generatedResult.title.toLowerCase().replace(/\s+/g, '_')}.${langObj.ext}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Compile standalone HTML for preview if needed
  const getRenderableHtml = () => {
    if (!generatedResult) return '';
    if (generatedResult.previewHtml && generatedResult.previewHtml.includes('<')) {
      return generatedResult.previewHtml;
    }
    // Fallback wrapper for raw HTML/JS
    return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
  <style>
    body { background-color: #0B0D0E; color: #f3f4f6; font-family: system-ui, -apple-system, sans-serif; padding: 20px; }
  </style>
</head>
<body>
  ${generatedResult.code}
</body>
</html>`;
  };

  return (
    <div id="farhee-code-gen-view" className="flex flex-col h-[calc(100vh-4rem)] bg-[#0B0D0E] overflow-y-auto">
      {/* Top Generator Input Control Box */}
      <div className="p-4 lg:p-6 border-b border-[#1A2227] bg-[#0E1317]/80 backdrop-blur-md">
        <div className="max-w-6xl mx-auto space-y-4">
          {/* Language selector chips */}
          <div className="flex items-center gap-2 overflow-x-auto pb-1 scrollbar-none">
            <span className="text-xs font-mono uppercase text-neutral-400 whitespace-nowrap flex items-center gap-1">
              <FileCode className="w-3.5 h-3.5 text-[#CCFF00]" /> Target Language:
            </span>
            {LANGUAGES.map((lang) => (
              <button
                key={lang.id}
                onClick={() => setSelectedLang(lang.id)}
                className={`px-3 py-1.5 rounded-xl text-xs font-mono font-medium transition-all whitespace-nowrap border ${
                  selectedLang === lang.id
                    ? 'bg-[#10B981]/20 border-[#10B981] text-[#CCFF00] shadow-md shadow-[#10B981]/15'
                    : 'bg-[#141A1E] border-[#222C33] text-neutral-400 hover:text-white hover:border-neutral-600'
                }`}
              >
                {lang.label}
              </button>
            ))}
          </div>

          {/* Prompt input and Framework */}
          <div className="flex flex-col md:flex-row gap-3">
            <div className="flex-1 relative">
              <input
                id="code-prompt-input"
                type="text"
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleGenerate()}
                placeholder={`Describe what you want Farhee to code in ${selectedLang}...`}
                className="w-full pl-4 pr-10 py-3 bg-[#12171B] border border-[#202B32] focus:border-[#10B981] focus:ring-1 focus:ring-[#10B981] rounded-xl text-sm text-neutral-100 placeholder:text-neutral-500 outline-none transition-all shadow-inner"
              />
              <button
                onClick={() => setPrompt('')}
                className="absolute right-3 top-3.5 text-neutral-500 hover:text-white text-xs"
              >
                ✕
              </button>
            </div>

            <div className="flex gap-2">
              <input
                type="text"
                value={framework}
                onChange={(e) => setFramework(e.target.value)}
                placeholder="Framework (e.g. Tailwind, Node, PyTorch)"
                className="w-44 px-3 py-3 bg-[#12171B] border border-[#202B32] focus:border-[#10B981] rounded-xl text-xs text-neutral-200 outline-none hidden sm:block"
              />

              <button
                id="generate-code-btn"
                onClick={() => handleGenerate()}
                disabled={isLoading || !prompt.trim()}
                className={`px-5 py-3 rounded-xl flex items-center justify-center gap-2 text-xs font-bold transition-all ${
                  isLoading
                    ? 'bg-[#1A2329] text-neutral-500 cursor-wait'
                    : 'bg-gradient-to-r from-[#10B981] to-[#CCFF00] text-black hover:opacity-95 shadow-lg shadow-[#10B981]/20 active:scale-95'
                }`}
              >
                {isLoading ? (
                  <>
                    <RefreshCw className="w-4 h-4 animate-spin text-[#CCFF00]" />
                    <span>Synthesizing...</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="w-4 h-4" />
                    <span>Generate Code</span>
                  </>
                )}
              </button>
            </div>
          </div>

          {/* Quick template suggestions */}
          <div className="flex items-center gap-2 overflow-x-auto text-[11px] text-neutral-400">
            <span className="font-mono text-neutral-400 uppercase">Ideas:</span>
            <button
              onClick={() => {
                setPrompt('Interactive Glassmorphic Crypto Card with live price fluctuation, neon lime glowing accents, and copy address button.');
                handleGenerate('Interactive Glassmorphic Crypto Card with live price fluctuation, neon lime glowing accents, and copy address button.');
              }}
              className="px-2.5 py-1 rounded-lg bg-[#141A1E] hover:bg-[#1C252B] border border-[#222C33] hover:border-[#10B981]/40 text-neutral-300 hover:text-[#CCFF00] whitespace-nowrap"
            >
              Glassmorphic Crypto Card
            </button>
            <button
              onClick={() => {
                setPrompt('Modern responsive navigation bar with mobile drawer, theme toggle, and search shortcut.');
                handleGenerate('Modern responsive navigation bar with mobile drawer, theme toggle, and search shortcut.');
              }}
              className="px-2.5 py-1 rounded-lg bg-[#141A1E] hover:bg-[#1C252B] border border-[#222C33] hover:border-[#10B981]/40 text-neutral-300 hover:text-[#CCFF00] whitespace-nowrap"
            >
              Responsive Header Bar
            </button>
            <button
              onClick={() => {
                setPrompt('Fast animated multi-step onboarding wizard with progress bar and validation.');
                handleGenerate('Fast animated multi-step onboarding wizard with progress bar and validation.');
              }}
              className="px-2.5 py-1 rounded-lg bg-[#141A1E] hover:bg-[#1C252B] border border-[#222C33] hover:border-[#10B981]/40 text-neutral-300 hover:text-[#CCFF00] whitespace-nowrap"
            >
              Step-by-step Wizard
            </button>
          </div>
        </div>
      </div>

      {/* Main Workspace Area (Code View + Live Preview + Explanation) */}
      <div className="flex-1 p-4 lg:p-6 max-w-6xl w-full mx-auto flex flex-col space-y-4">
        {generatedResult ? (
          <div className="flex-1 flex flex-col rounded-2xl bg-[#0E1317] border border-[#1E272D] overflow-hidden shadow-2xl">
            {/* Window title bar & View Toggle */}
            <div className="px-4 py-3 bg-[#13191D] border-b border-[#1E272D] flex flex-wrap items-center justify-between gap-3">
              <div className="flex items-center gap-3">
                {/* Traffic dots */}
                <div className="flex items-center gap-1.5">
                  <div className="w-3 h-3 rounded-full bg-red-500/80" />
                  <div className="w-3 h-3 rounded-full bg-amber-500/80" />
                  <div className="w-3 h-3 rounded-full bg-emerald-500/80" />
                </div>
                <div className="h-4 w-[1px] bg-[#222D35]" />
                <span className="text-xs font-mono font-bold text-white flex items-center gap-1.5">
                  <Code2 className="w-4 h-4 text-[#CCFF00]" />
                  {generatedResult.title}
                </span>
                <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-[#10B981]/15 text-[#CCFF00] border border-[#10B981]/30">
                  {generatedResult.language}
                </span>
              </div>

              {/* Center Tabs: Code vs Live Preview vs Explanation */}
              <div className="flex items-center p-1 rounded-xl bg-[#090C0E] border border-[#1E272D]">
                <button
                  id="tab-code-view"
                  onClick={() => setActiveTab('code')}
                  className={`px-3 py-1 rounded-lg text-xs font-mono font-medium flex items-center gap-1.5 transition-colors ${
                    activeTab === 'code'
                      ? 'bg-[#182229] text-[#CCFF00] border border-[#10B981]/40'
                      : 'text-neutral-400 hover:text-white'
                  }`}
                >
                  <Code2 className="w-3.5 h-3.5" />
                  <span>Code</span>
                </button>

                <button
                  id="tab-preview-view"
                  onClick={() => setActiveTab('preview')}
                  className={`px-3 py-1 rounded-lg text-xs font-mono font-medium flex items-center gap-1.5 transition-colors ${
                    activeTab === 'preview'
                      ? 'bg-[#10B981]/20 text-[#CCFF00] border border-[#10B981]/40'
                      : 'text-neutral-400 hover:text-white'
                  }`}
                >
                  <Eye className="w-3.5 h-3.5 text-[#10B981]" />
                  <span>Live Preview</span>
                </button>

                <button
                  id="tab-explanation-view"
                  onClick={() => setActiveTab('explanation')}
                  className={`px-3 py-1 rounded-lg text-xs font-mono font-medium flex items-center gap-1.5 transition-colors ${
                    activeTab === 'explanation'
                      ? 'bg-[#182229] text-emerald-300 border border-[#10B981]/40'
                      : 'text-neutral-400 hover:text-white'
                  }`}
                >
                  <Sparkles className="w-3.5 h-3.5" />
                  <span>Architecture</span>
                </button>
              </div>

              {/* Action Buttons: Copy & Download */}
              <div className="flex items-center gap-2">
                <button
                  id="copy-code-btn"
                  onClick={handleCopyCode}
                  className="px-3 py-1.5 rounded-lg bg-[#182126] hover:bg-[#202C33] border border-[#26343D] text-xs text-neutral-200 hover:text-[#CCFF00] flex items-center gap-1.5 transition-colors"
                >
                  {copied ? (
                    <>
                      <Check className="w-3.5 h-3.5 text-[#CCFF00]" />
                      <span className="text-[#CCFF00]">Copied!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-3.5 h-3.5 text-[#10B981]" />
                      <span>Copy Code</span>
                    </>
                  )}
                </button>

                <button
                  id="download-code-file-btn"
                  onClick={handleDownloadFile}
                  className="p-1.5 px-2.5 rounded-lg bg-[#182126] hover:bg-[#202C33] border border-[#26343D] text-xs text-neutral-300 hover:text-white flex items-center gap-1.5 transition-colors"
                  title="Download File"
                >
                  <Download className="w-3.5 h-3.5 text-[#10B981]" />
                  <span className="hidden sm:inline">Save</span>
                </button>
              </div>
            </div>

            {/* Tab Contents */}
            <div className="flex-1 p-4 bg-[#090C0E] overflow-auto min-h-[420px]">
              {activeTab === 'code' && (
                <div className="relative">
                  <pre className="font-mono text-xs sm:text-sm text-neutral-200 leading-relaxed overflow-x-auto p-4 rounded-xl bg-[#0B0E10] border border-[#1A2227]">
                    <code>{generatedResult.code}</code>
                  </pre>
                </div>
              )}

              {activeTab === 'preview' && (
                <div className="w-full h-full min-h-[460px] flex flex-col rounded-xl overflow-hidden border border-[#1E272D] bg-[#0B0D0E]">
                  <div className="px-4 py-2 bg-[#12181C] border-b border-[#1E272D] flex items-center justify-between text-xs text-neutral-400">
                    <span className="font-mono flex items-center gap-1.5 text-emerald-400">
                      <Play className="w-3.5 h-3.5 text-[#CCFF00]" />
                      Sandbox Runtime (HTML5 / Tailwind CSS / JS)
                    </span>
                    <button
                      onClick={() => {
                        if (previewIframeRef.current) {
                          previewIframeRef.current.srcdoc = getRenderableHtml();
                        }
                      }}
                      className="hover:text-white flex items-center gap-1 text-[11px] font-mono"
                    >
                      <RefreshCw className="w-3 h-3 text-[#10B981]" /> Reload Preview
                    </button>
                  </div>
                  <iframe
                    ref={previewIframeRef}
                    title="Live Preview"
                    sandbox="allow-scripts allow-modals"
                    srcDoc={getRenderableHtml()}
                    className="w-full flex-1 min-h-[420px] bg-[#0B0D0E] border-none"
                  />
                </div>
              )}

              {activeTab === 'explanation' && (
                <div className="p-4 rounded-xl bg-[#0E1317] border border-[#1E272D] text-sm text-neutral-200 space-y-4">
                  <div>
                    <h4 className="text-xs font-bold uppercase tracking-wider text-[#CCFF00] font-mono mb-2">
                      Architectural Overview & Implementation
                    </h4>
                    <div className="prose prose-invert prose-sm max-w-none">
                      <ReactMarkdown>{generatedResult.explanation}</ReactMarkdown>
                    </div>
                  </div>

                  {generatedResult.features && generatedResult.features.length > 0 && (
                    <div className="pt-3 border-t border-[#1C252B]">
                      <h4 className="text-xs font-bold uppercase tracking-wider text-emerald-400 font-mono mb-2">
                        Key Engineering Features
                      </h4>
                      <ul className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs text-neutral-300">
                        {generatedResult.features.map((feat, idx) => (
                          <li key={idx} className="flex items-center gap-2 p-2 rounded-lg bg-[#13191D] border border-[#1F2930]">
                            <span className="w-1.5 h-1.5 rounded-full bg-[#CCFF00]"></span>
                            <span>{feat}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {generatedResult.dependencies && generatedResult.dependencies.length > 0 && (
                    <div className="pt-3 border-t border-[#1C252B]">
                      <h4 className="text-xs font-bold uppercase tracking-wider text-neutral-400 font-mono mb-2">
                        Dependencies
                      </h4>
                      <div className="flex flex-wrap gap-2">
                        {generatedResult.dependencies.map((dep, idx) => (
                          <span key={idx} className="px-2.5 py-1 rounded-md bg-[#13191D] text-[#CCFF00] font-mono text-xs border border-[#1F2930]">
                            {dep}
                          </span>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>
        ) : (
          <div className="flex-1 flex flex-col items-center justify-center p-12 text-center rounded-2xl bg-[#0E1317]/50 border border-dashed border-[#1E272D] space-y-4">
            <div className="w-14 h-14 rounded-2xl bg-gradient-to-tr from-[#10B981]/20 to-[#CCFF00]/10 border border-[#10B981]/30 flex items-center justify-center text-[#CCFF00]">
              <Code2 className="w-7 h-7" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white font-display">Farhee Code Generation Engine</h3>
              <p className="text-xs text-neutral-400 max-w-md mt-1">
                Select your language above and describe your desired component or backend script. Farhee will generate clean code, tests, and a live preview.
              </p>
            </div>
            <button
              onClick={() => handleGenerate()}
              className="px-4 py-2 rounded-xl bg-[#10B981]/20 border border-[#10B981]/50 text-[#CCFF00] text-xs font-semibold hover:bg-[#10B981]/30 transition-all flex items-center gap-1.5"
            >
              <Sparkles className="w-3.5 h-3.5" />
              Generate Sample React Component
            </button>
          </div>
        )}
      </div>
    </div>
  );
};
